CREATE TABLE accepted_letter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    letter_id UUID NOT NULL UNIQUE,
    letter_type VARCHAR(25),
    sender_type VARCHAR(25),
    getter_id UUID,
    getter_type VARCHAR(25)
);

CREATE TABLE event_outbox (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_name VARCHAR(50) NOT NULL,
    letter_id UUID NOT NULL UNIQUE,
    created_datetime TIMESTAMP NOT NULL,
    status VARCHAR(25)
);
